/* Fluent English – word + IPA text engine.
 *
 * Every English word is rendered as its own unit (word on top, IPA directly beneath),
 * so the pair wraps together. Punctuation stays attached to the word and receives no IPA.
 *
 * Inline markup in lesson strings:
 *   *text*        highlight (target vocabulary)
 *   word{ipa}     explicit pronunciation for one word (heteronyms such as read{red})
 *   \n            line break
 *
 * IPA comes from FE.LEX_IPA (generated by tools/build-lexicon.mjs).
 */
(function (root) {
  "use strict";
  var FE = (root.FE = root.FE || {});
  FE.LEX_IPA = FE.LEX_IPA || {};
  FE.missingIpa = FE.missingIpa || {};

  var WORD_RE = /[A-Za-zÀ-ÿ]+(?:['’][A-Za-z]+)*(?:-[A-Za-z]+(?:['’][A-Za-z]+)*)*/;

  function keyOf(w) {
    return String(w).toLowerCase().replace(/’/g, "'");
  }
  FE.keyOf = keyOf;

  function esc(s) {
    return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  }
  FE.esc = esc;

  /* Split a lesson string into tokens.
   * token = {type:'word', text, key, ipa?, hl, c0, c1} | {type:'punct', text} | {type:'space'} | {type:'br'} */
  function tokenize(str) {
    var out = [];
    var hl = false;
    var plainPos = 0; // offset in the plain (spoken) text
    var i = 0;
    var s = String(str);
    while (i < s.length) {
      var ch = s[i];
      if (ch === "\n") { out.push({ type: "br" }); plainPos += 1; i++; continue; }
      if (ch === "*") { hl = !hl; i++; continue; }
      if (/\s/.test(ch)) {
        out.push({ type: "space" });
        while (i < s.length && /\s/.test(s[i]) && s[i] !== "\n") i++;
        plainPos += 1;
        continue;
      }
      var m = s.slice(i).match(new RegExp("^" + WORD_RE.source));
      if (m) {
        var text = m[0];
        i += text.length;
        var tok = { type: "word", text: text, key: keyOf(text), hl: hl, c0: plainPos, c1: plainPos + text.length };
        if (s[i] === "{") {
          var close = s.indexOf("}", i);
          if (close > i) { tok.ipa = s.slice(i + 1, close); i = close + 1; }
        }
        plainPos += text.length;
        out.push(tok);
        continue;
      }
      // punctuation / digits / symbols
      out.push({ type: "punct", text: ch });
      plainPos += ch === "\u2026" ? 3 : 1;
      i++;
    }
    return out;
  }
  FE.tokenize = tokenize;

  /* Text exactly as it should be spoken (markup removed). */
  function plain(str) {
    var t = tokenize(str);
    var s = "";
    t.forEach(function (k) {
      if (k.type === "word") s += k.text;
      else if (k.type === "space") s += " ";
      else if (k.type === "br") s += "\n";
      else s += k.text;
    });
    return s.replace(/…/g, "...").replace(/\s+\n/g, "\n");
  }
  FE.plain = plain;

  /* Context rules that change a pronunciation: "used to" -> /juːst/, "(did) use to" -> /juːs/ */
  function contextIpa(words, idx) {
    var w = words[idx];
    var next = words[idx + 1];
    var prev = words[idx - 1];
    if (w.key === "used" && next && next.key === "to") return "juːst";
    if (w.key === "use" && next && next.key === "to" && prev && /^(did|didn't|didn’t)$/.test(prev.key)) return "juːs";
    return null;
  }

  function ipaFor(tok, words, idx) {
    if (tok.ipa) return tok.ipa;
    var c = contextIpa(words, idx);
    if (c) return c;
    var v = FE.LEX_IPA[tok.key];
    if (v) return v;
    FE.missingIpa[tok.key] = true;
    return null;
  }
  FE.ipaFor = function (key) { return FE.LEX_IPA[keyOf(key)] || null; };

  /* Render to HTML.  opts: {cls, bare}  – bare: no wrapper span.
   * Tokens are grouped into clusters between spaces; punctuation inside a cluster is attached to the
   * nearest word (leading punctuation to the first word, everything else to the word before it). */
  function unit(k, ipa, pre, post) {
    var cls = "wu" + (k.hl ? " hl" : "") + (ipa ? "" : " noipa");
    return '<span class="' + cls + '" data-w="' + esc(k.key) + '" data-c0="' + k.c0 + '" data-c1="' + k.c1 + '">' +
      '<span class="wt">' + esc(pre + k.text + post) + "</span>" +
      '<span class="wi" aria-hidden="true">' + (ipa ? "/" + esc(ipa) + "/" : "\u00B7") + "</span></span>";
  }

  function t(str, opts) {
    opts = opts || {};
    var toks = tokenize(str);
    var words = toks.filter(function (k) { return k.type === "word"; });
    var html = "";
    var wi = 0;
    var cluster = [];
    function flush() {
      if (!cluster.length) return;
      var hasWord = cluster.some(function (k) { return k.type === "word"; });
      if (!hasWord) {
        html += '<span class="wu wp"><span class="wt">' + esc(cluster.map(function (k) { return k.text; }).join("")) + "</span></span>";
      } else {
        var pre = "";
        var seenWord = false;
        for (var i = 0; i < cluster.length; i++) {
          var k = cluster[i];
          if (k.type === "punct" && !seenWord) { pre += k.text; continue; }
          if (k.type !== "word") continue;
          seenWord = true;
          var post = "";
          var j = i + 1;
          while (j < cluster.length && cluster[j].type === "punct") { post += cluster[j].text; j++; }
          html += unit(k, ipaFor(k, words, wi++), pre, post);
          pre = "";
          i = j - 1;
        }
      }
      cluster = [];
    }
    toks.forEach(function (k) {
      if (k.type === "br") { flush(); html += "<br>"; }
      else if (k.type === "space") flush();
      else cluster.push(k);
    });
    flush();
    if (opts.bare) return html;
    return '<span class="tx' + (opts.cls ? " " + opts.cls : "") + '" data-plain="' + esc(plain(str)) + '">' + html + "</span>";
  }
  FE.t = t;

  /* All displayed English words in a string (used by tests / tools). */
  FE.wordsIn = function (str) {
    return tokenize(str).filter(function (k) { return k.type === "word"; }).map(function (k) { return k.key; });
  };

  if (typeof module !== "undefined" && module.exports) module.exports = FE;
})(typeof window !== "undefined" ? window : globalThis);
