/* Every English label shown by the interface lives here so that each word gets its IPA. */
(function (root) {
  "use strict";
  var FE = (root.FE = root.FE || {});
  FE.S = {
    lessonTitle: "Childhood: Memories, Games, and Growing Up",
    club: "Speaking Club",
    tagline: "Keep Speaking. Keep Growing.",
    chapter: "Chapter",

    /* controls bar */
    cPrevChapter: "Chapter", cBack: "Back", cPlay: "Play", cPause: "Pause", cNext: "Next", cNextChapter: "Chapter",
    cReplay: "Replay", cTimer: "Timer", cStart: "Start", cStop: "Pause", cReset: "Reset",
    cReveal: "Reveal", cStarters: "Starters", cExample: "Example", cWords: "Words", cChapters: "Chapters",
    cNotes: "Notes", cMode: "Mode", cClass: "Class", cDemo: "Demo", cVolume: "Volume", cFull: "Full screen", cExitFull: "Exit",
    cSettings: "Settings", cHide: "Hide controls", cShow: "Show controls", cClose: "Close", cSkip: "Skip",
    aPrevChapter: "Previous chapter", aNextChapter: "Next chapter", aBack: "Previous step", aNext: "Next step",
    aTimerMinus: "Subtract thirty seconds", aTimerPlus: "Add thirty seconds",

    /* HUD labels */
    sampleTag: "Sample response (fictional)",
    exampleTag: "Fictional example",
    modelTag: "Model conversation",
    listen: "Listen",
    passOk: "Pass is always okay.",

    /* start screen */
    startTitle: "Choose how to run the lesson",
    classModeT: "Class Mode",
    classModeD: "The lesson pauses for your students until you continue.",
    demoModeT: "Demo Mode",
    demoModeD: "A hands-free preview with fictional sample responses and shorter timers.",
    startClass: "Start Class Mode",
    startDemo: "Start Demo Mode",
    startTime: "Planned time: sixty minutes. Real discussion, questions, and technical pauses can make the actual lesson longer.",
    audioCheck: "Audio check",
    audioTest: "Test the voice",
    audioNone: "No English voice was found. The lesson will run with captions and a script.",
    audioOk: "English voices found:",
    tipH: "Press H to hide or show the controls.",
    tipDbl: "Double-click any word for its meaning, an example, and audio.",
    tipShare: "Share your screen in Zoom, then press F for full screen.",

    /* plan overlay */
    planTitle: "Lesson plan: sixty minutes",
    planCols: ["Chapter", "Minutes", "Student speaking", "Internal timing"],
    planNote: "Timers are planned times. Class Mode waits for you, so real discussion can extend the lesson.",
    planSpeak: "Student speaking in the plan",
    planTotal: "Total",
    planGo: "Go to this chapter",
    minutes: "minutes",
    min: "min",
    sec: "seconds",

    /* notes drawer */
    nTitle: "Teacher notes",
    nTabs: ["Tally", "Marks", "Notes", "Data"],
    nTallyNote: "Choices are counted by the teacher. Nothing is listened to or graded automatically.",
    nNoTally: "No choices recorded yet.",
    nMarksNote: "Anonymous participation marks by the teacher. Please do not use full names.",
    nMarkCols: ["Speaking", "Clear reason", "Vocabulary", "Listening"],
    nNotesNote: "Private teacher notes. Please do not type private stories or personal details.",
    nDataNote: "Nothing is saved by default. Notes and marks stay in this browser tab until you leave.",
    nSave: "Save notes and marks on this computer",
    nSaveWarn: "Local save uses this browser only. It is not cloud sync and not Google Sheets.",
    nExportJson: "Export JSON",
    nExportCsv: "Export CSV",
    nResetAll: "Reset all notes",
    nObs: "These are teacher observations, not automatic assessment.",
    nClean: "Clear",
    nConfirm: "Press again to confirm.",

    /* settings */
    sTitle: "Settings",
    sVoices: "Narration voices",
    sVoiceNone: "No English voice available in this browser.",
    sAudition: "Audition",
    sNarr: "Narration",
    sOn: "On", sOff: "Off",
    sMusic: "Background music",
    sMusicD: "Original, soft, and optional.",
    sMusicVol: "Music volume",
    sSfx: "Sound effects",
    sAuto: "Start speaking timers automatically",
    sDemoSec: "Demo timer length",
    sMotion: "Reduce motion",
    sShort: "Keyboard shortcuts",
    sScript: "Narration script",
    sChart: "Sound chart",
    sAbout: "About the pronunciation",
    sRate: "Speaking speed",
    sRoles: { maya: "Maya", theo: "Theo", alex: "Alex", jordan: "Jordan" },
    sReset: "Reset settings",

    /* help */
    hTitle: "Keyboard shortcuts",
    hKeys: [["Space", "Play or pause"], ["Right arrow", "Next step"], ["Left arrow", "Previous step"], ["Shift and right arrow", "Next chapter"],
            ["Shift and left arrow", "Previous chapter"], ["R", "Replay this step"], ["T", "Start or pause the timer"], ["N", "Reveal the next item"],
            ["S", "Show sentence starters"], ["E", "Show a fictional example"], ["H", "Hide or show the controls"], ["F", "Full screen"], ["W", "Word banks"], ["J", "Add a star to the memory jar"], ["Question mark", "This list"]],

    /* about pronunciation */
    aboutTitle: "About the pronunciation",
    aboutLines: [
      "The symbols match the Fluent English sound chart, which uses the same symbols as Oxford Learner's Dictionaries American English.",
      "Each transcription was produced automatically from an American English pronunciation dictionary and converted to those symbols.",
      "It has not been checked word by word against Oxford Learner's Dictionaries. Treat unusual words with care.",
      "Names such as Maya and Theo have no dictionary entry and were set by the author.",
    ],

    /* dictionary popover */
    dictMeaning: "Meaning",
    dictExample: "Example",
    dictPlay: "Play all",
    dictWord: "Word",
    dictStop: "Stop",
    dictNone: "No lesson definition for this word yet.",
    dictForm: "form of",

    /* widgets */
    scaleLabel: "Class choices, counted by the teacher",
    scaleHint: "Click a choice to add one. Shift-click removes one.",
    rankUp: "Move up", rankDown: "Move down", rankTop: "First", rankReset: "Reset order", rankLock: "Top two",
    rankKeys: "Drag a card, or use the buttons.",
    wyrChoose: "Class choices",
    wyrAgain: "After the twist",
    bankTitle: "Optional word banks",
    bankMore: "Show more",
    bankDone: "All words shown.",
    planSlot: "Activity",
    planMin: "Minutes",
    planBackup: "Backup plan",
    planTotal2: "Total time",
    planPick: "Choose an activity",
    constraintNext: "Next constraint",
    rubricTitle: "Rubric",
    rubricCrit: ["Clarity", "Interaction", "Vocabulary", "Relevant accuracy"],
    rubricLevels: ["Emerging", "Developing", "Secure", "Strong"],
    rubricNote: "Teacher observation only. The lesson does not assess speaking or pronunciation automatically.",
    rubricWho: "Speaker",
    verSupported: "Supported",
    verSupportedD: "At first… Then… In the end… Use two sentences.",
    verStandard: "Standard",
    verStandardD: "Thirty seconds. One routine or event, two expressions, a clear ending, and a follow-up question.",
    verLonger: "Longer challenge",
    verLongerD: "Sixty seconds. Add a feeling, a lesson, and one use of would for a repeated action.",
    revealHint: "Reveal next",
    showAnswer: "Answer",
    optResult: "Possible result (fictional)",
    chooseA: "A", chooseB: "B",
    closing: "Thank you for speaking today.",
    roleCardA: "Role card",
    shownToAll: "Visible to everyone",
    goalLabel: "Your goal",
    taskLabel: "Task",
    scriptTitle: "Narration script",
    scriptNote: "If your computer has no English voice, read these lines aloud or let the captions run.",
    chartTitle: "Sound chart",
    reflectHint: "Click to count an expression.",
    loading: "Loading",
    answerLabel: "The answer:", drawCard: "Draw a card", drawAgain: "Draw again",
    cStar: "Star", aStar: "Add a speaking star to the memory jar",
    jarFull: "The memory jar is full!", jarTitle: "Memory jar", starNote: "Add a star when someone speaks, asks a question, or helps.",
    sCelebrate: "Celebrate when time is up",
    cheers: ["Time! Great speaking, everyone!", "Wonderful! Thank you for sharing.", "Nice work! Every sentence counts.", "That was brave. Well done!", "Great ideas! Time is up."],
    startMusic: "Play soft background music", startSfx: "Play sound effects",
    yourTurn: "Your turn", twist: "Twist", wyrHead: "Would you rather…?", orWord: "or", go: "Go",
    claimLbl: "Claim", roundLbl: "Round", rankingLbl: "Ranking", reuseLbl: "Expressions to reuse",
    demoShort: "Demo Mode", aboutDot: "Words with a faint dot below them have no transcription yet.",
    hello: "Hello! I'm", audLine: "This is how I sound in the lesson.", welcomeTest: "Welcome to Speaking Club. This is how the narration will sound.",
  };
})(typeof window !== "undefined" ? window : globalThis);
