/* Fluent English - Love Speaking Club
 * ipa.js : renders English text as separate word+IPA units that wrap together.
 *   I('Text with *highlight* and word~variant.')  ->  HTML string
 * Every displayed English word is a unit: the word on top, its IPA directly beneath. Punctuation gets no IPA.
 * The dictionary (ipa-data.js) is generated by tools/build-ipa.mjs - see docs/IPA-METHOD.md for how it was made and
 * what has and has not been verified against Oxford Learner's Dictionaries (American English).
 */
(function (g) {
  'use strict';
  const D = g.IPA_DICT || {};
  const seen = new Set(); const missing = new Set();
  const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  const LEAD = /^[“‘"'(\[]+/;
  const TRAIL = /[.,!?:;”’"')\]…—–]+$/;
  const PUNCT_ONLY = /^[.,!?:;”’“‘"'()\[\]…—–−\-•·\/+=&|✓▲▼→]+$/;
  const CLOCK = /^\d{1,2}:\d{2}$/;
  const NUMERIC = /^[\d][\d:.,%]*$/;

  function lookupKey(key) {
    if (D[key] !== undefined) return D[key];
    if (key.indexOf('-') > 0) {
      const parts = key.split('-'); const out = [];
      for (const p of parts) { if (D[p] === undefined) return undefined; out.push(D[p]); }
      return out.join(' ');
    }
    return undefined;
  }

  function unit(core, ipa, hl, lead, trail, miss) {
    const w = esc(lead + core + trail);
    const p = ipa === null ? '' : `<span class="p${miss ? ' miss' : ''}" aria-hidden="true">${miss ? '/?/' : '/' + esc(ipa) + '/'}</span>`;
    return `<span class="wu${hl ? ' hl' : ''}"><span class="w">${w}</span>${p}</span>`;
  }

  function I(text, opt) {
    opt = opt || {};
    if (text == null) return '';
    const marked = String(text).replace(/\*([^*]+)\*/g, '\u0001$1\u0002');
    const lines = marked.split('\n'); const outLines = [];
    let hl = false;
    for (const line of lines) {
      const toks = line.split(/\s+/).filter(Boolean); const out = [];
      for (let tok of toks) {
        let tokHl = hl;
        if (tok.indexOf('\u0001') >= 0) { hl = true; tokHl = true; tok = tok.replace(/\u0001/g, ''); }
        if (tok.indexOf('\u0002') >= 0) { hl = false; tok = tok.replace(/\u0002/g, ''); }
        if (!tok) continue;
        if (PUNCT_ONLY.test(tok)) { out.push(`<span class="pu">${esc(tok)}</span>`); continue; }
        if (CLOCK.test(tok)) { out.push(`<span class="pu num">${esc(tok)}</span>`); continue; }
        let lead = '', trail = '', core = tok;
        const lm = core.match(LEAD); if (lm) { lead = lm[0]; core = core.slice(lead.length); }
        const tm = core.match(TRAIL); if (tm) { trail = tm[0]; core = core.slice(0, core.length - trail.length); }
        if (!core) { out.push(`<span class="pu">${esc(tok)}</span>`); continue; }
        let shown = core, key = core.replace(/’/g, "'").toLowerCase();
        const vi = key.indexOf('~'); if (vi > 0) { shown = core.slice(0, core.indexOf('~')); }
        seen.add(key);
        const ipa = lookupKey(key);
        if (ipa === undefined) { missing.add(key); out.push(unit(shown, ipa === undefined ? '' : ipa, tokHl, lead, trail, true)); }
        else out.push(unit(shown, ipa, tokHl, lead, trail, false));
      }
      outLines.push(out.join(' '));
    }
    const html = outLines.join('<br>');
    return opt.block ? `<span class="txt${opt.center ? ' center' : ''}">${html}</span>` : html;
  }
  /* strings that are not English words (clock readouts, numerals alone) */
  I.raw = (s) => esc(s);
  I.seen = () => [...seen]; I.missing = () => [...missing];
  I.hasDict = () => Object.keys(D).length;
  g.I = I;
})(window);
