// Builds js/lexicon-ipa.js and js/lexicon-def.js.
//   node tools/build-lexicon.mjs
// Inputs : lesson/UI string literals (scanned), tools/displayed-words.json (from tools/crawl.mjs),
//          tools/ipa-overrides.json, tools/glossary.txt, tools/forms.txt
// IPA    : overrides first, otherwise the CMU Pronouncing Dictionary converted to Sound Chart symbols (tools/ipa.mjs).
//          Nothing here is checked word-by-word against Oxford Learner's Dictionaries.
import fs from "fs";
import path from "path";
import vm from "vm";
import { fileURLToPath } from "url";
import { cmuLookup, cmuRaw } from "./ipa.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const read = (p) => fs.readFileSync(path.resolve(root, p), "utf8");

// load the same tokenizer the page uses
const ctx = { window: {}, globalThis: {} };
ctx.window = ctx; vm.createContext(ctx);
vm.runInContext(read("js/text.js"), ctx);
const FE = ctx.FE;

/* ---- 1. collect words from string literals in the lesson sources ---- */
function stringLiterals(src) {
  const out = [];
  const re = /"((?:[^"\\\n]|\\.)*)"|'((?:[^'\\\n]|\\.)*)'/g;
  let m;
  while ((m = re.exec(src))) out.push(m[1] !== undefined ? m[1] : m[2]);
  return out;
}
const sources = ["js/ui-strings.js", "js/data-1.js", "js/data-2.js", "js/data-3.js", "js/app-core.js", "js/app-widgets.js", "js/app-run.js"];
const words = new Map(); // key -> {count}
function addWords(str, from) {
  let s = str;
  try { s = JSON.parse('"' + str.replace(/"/g, '\\"') + '"'); } catch (e) {}
  for (const w of FE.wordsIn(s)) { if (w.length) words.set(w, (words.get(w) || 0) + 1); }
}
for (const f of sources) for (const s of stringLiterals(read(f))) if (/[A-Za-z]{2,}/.test(s) && !/^[#.\w-]*$|[<>=;{}]/.test(s.replace(/'\s/g, ""))) addWords(s, f);
// dynamically built strings in data files (e.g. "Word 1: ...", vocabulary words)
const crawlPath = path.resolve(here, "displayed-words.json");
let crawl = {};
if (fs.existsSync(crawlPath)) crawl = JSON.parse(fs.readFileSync(crawlPath, "utf8"));
for (const k of Object.keys(crawl)) words.set(k, (words.get(k) || 0) + 1);

/* ---- 2. glossary (definitions, examples) ---- */
const gloss = new Map();      // lemma -> {pos, def, ex}
const glossPath = path.resolve(here, "glossary.txt");
if (fs.existsSync(glossPath)) {
  for (const line of fs.readFileSync(glossPath, "utf8").split("\n")) {
    if (!line.trim() || line.startsWith("#")) continue;
    const parts = line.split("|").map((x) => x.trim());
    if (parts.length < 4) { console.warn("bad glossary line:", line); continue; }
    gloss.set(parts[0].toLowerCase(), { pos: parts[1], def: parts[2], ex: parts.slice(3).join("|") });
  }
}
const forms = new Map();      // surface -> lemma
const formsPath = path.resolve(here, "forms.txt");
if (fs.existsSync(formsPath)) {
  for (const line of fs.readFileSync(formsPath, "utf8").split("\n")) {
    if (!line.trim() || line.startsWith("#")) continue;
    const [lemma, list] = line.split(":").map((x) => x.trim());
    for (const f of list.split(/[,\s]+/).filter(Boolean)) forms.set(f.toLowerCase(), lemma.toLowerCase());
  }
}
// words used in glossary text also need IPA (they are shown in the double-click popover)
for (const [k, g] of gloss) { for (const w of FE.wordsIn(k)) words.set(w, (words.get(w) || 0) + 1); for (const w of FE.wordsIn(g.def + " " + g.ex)) words.set(w, (words.get(w) || 0) + 1); }

/* ---- 3. IPA ---- */
const overrides = JSON.parse(fs.readFileSync(path.resolve(here, "ipa-overrides.json"), "utf8"));
function stressPart(ipa, first) { // demote primary stress to secondary for non-initial compound parts
  return first ? ipa : ipa.replace(/ˈ/g, "ˌ");
}
const ipa = {}, source = {}, missing = [];
for (const w of [...words.keys()].sort()) {
  if (overrides[w] !== undefined) { ipa[w] = overrides[w]; source[w] = "author"; continue; }
  let v = cmuLookup(w);
  if (v) { ipa[w] = v; source[w] = "cmu"; continue; }
  if (w.includes("-")) {
    const parts = w.split("-");
    const ps = parts.map((p) => overrides[p] ?? cmuLookup(p));
    if (ps.every(Boolean)) { ipa[w] = ps.map((p, i) => stressPart(p, i === 0)).join(" "); source[w] = "cmu-compound"; continue; }
  }
  if (w.endsWith("'s")) { const b = overrides[w.slice(0, -2)] ?? cmuLookup(w.slice(0, -2)); if (b) { ipa[w] = b + (/[sʃʒz]$|tʃ$|dʒ$/.test(b) ? "ɪz" : /[ptkfθ]$/.test(b) ? "s" : "z"); source[w] = "cmu+'s"; continue; } }
  missing.push(w);
}
fs.writeFileSync(path.resolve(root, "js/lexicon-ipa.js"),
  "/* Generated by tools/build-lexicon.mjs. American English IPA in Sound Chart symbols.\n * Source: CMU Pronouncing Dictionary converted automatically, plus author overrides (names, heteronyms, weak forms).\n * NOT verified word by word against Oxford Learner's Dictionaries. */\nwindow.FE = window.FE || {};\nFE.LEX_IPA = " + JSON.stringify(ipa) + ";\n");

/* ---- 4. definitions ---- */
function lemmaOf(w) {
  if (gloss.has(w)) return w;
  if (forms.has(w) && gloss.has(forms.get(w))) return forms.get(w);
  const tries = [];
  if (w.endsWith("ies")) tries.push(w.slice(0, -3) + "y");
  if (w.endsWith("es")) tries.push(w.slice(0, -2));
  if (w.endsWith("s")) tries.push(w.slice(0, -1));
  if (w.endsWith("ied")) tries.push(w.slice(0, -3) + "y");
  if (w.endsWith("ed")) tries.push(w.slice(0, -2), w.slice(0, -1));
  if (w.endsWith("ing")) tries.push(w.slice(0, -3), w.slice(0, -3) + "e");
  if (w.endsWith("ly")) tries.push(w.slice(0, -2));
  if (w.endsWith("er")) tries.push(w.slice(0, -2), w.slice(0, -1));
  if (/(.)\1(ed|ing|er)$/.test(w)) tries.push(w.replace(/(.)\1(ed|ing|er)$/, "$1"));
  for (const t of tries) if (gloss.has(t)) return t;
  return null;
}
const defs = {}, noDef = [];
const displayed = Object.keys(crawl);
for (const w of displayed) {
  const l = lemmaOf(w);
  if (!l) { noDef.push(w); continue; }
  const g = gloss.get(l);
  defs[w] = { pos: g.pos, def: g.def, ex: g.ex, ...(l !== w ? { lemma: l } : {}) };
}
// phrase entries (multi-word) are keyed with spaces
const phrases = [];
for (const [k, g] of gloss) if (k.includes(" ") || k.includes("-")) { defs[k] = { pos: g.pos, def: g.def, ex: g.ex }; if (k.includes(" ")) phrases.push(k.split(" ")); }
// every word of a phrase should be clickable on its own as well; entries for those come from the glossary directly
fs.writeFileSync(path.resolve(root, "js/lexicon-def.js"),
  "/* Generated by tools/build-lexicon.mjs from tools/glossary.txt. Short learner definitions written for this lesson. */\nwindow.FE = window.FE || {};\nFE.LEX_DEF = " + JSON.stringify(defs) + ";\nFE.LEX_PHRASES = " + JSON.stringify(phrases) + ";\n");

const bySrc = {};
for (const w of Object.keys(source)) bySrc[source[w]] = (bySrc[source[w]] || 0) + 1;
console.log("words:", words.size, "ipa:", Object.keys(ipa).length, JSON.stringify(bySrc));
console.log("missing IPA:", missing.length, missing.join(" "));
console.log("displayed words:", displayed.length, "without definition:", noDef.length);
fs.writeFileSync(path.resolve(here, "missing-defs.txt"), noDef.join("\n") + "\n");
fs.writeFileSync(path.resolve(here, "ipa-report.json"), JSON.stringify({ bySrc, missing, author: Object.keys(source).filter((k) => source[k] === "author") }, null, 1));
