import { chromium } from "playwright-core";
import path from "path";
import { fileURLToPath } from "url";
const here = path.dirname(fileURLToPath(import.meta.url));
const url = "file://" + path.resolve(here, "../index.html");
const out = process.argv[2] || "/tmp";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium", args: ["--no-sandbox"] });
const p = await b.newPage({ viewport: { width: 1600, height: 900 } });
const errs = [];
p.on("console", (m) => (m.type() === "error" || m.type() === "warning") && errs.push(m.type() + ": " + m.text()));
p.on("pageerror", (e) => errs.push("PAGEERROR " + String(e)));
await p.goto(url);
await p.waitForTimeout(800);
await p.screenshot({ path: out + "/s0-start.png" });
await p.click('[data-start="class"]');
await p.waitForTimeout(1500);
await p.screenshot({ path: out + "/s1-open.png" });
console.log("errors:", errs.slice(0, 15));
await b.close();
