// Generates narration WAVs from LOCAL device speech engines and measures them.
//   English (American, male): flite voice "rms"   Spanish (Latin American): eSpeak NG "es-419"
// Output: build/voices/<id>.wav (44.1 kHz mono, silence-trimmed) + build/voices.json
const fs = require('fs'), path = require('path'), cp = require('child_process');
const vm = require('vm');
const root = path.resolve(__dirname, '..');
const sandbox = { window: {} }; vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(root, 'src/config.js'), 'utf8'), sandbox);
const FE = sandbox.window.FE;
const out = path.join(root, 'build/voices'); fs.mkdirSync(out, { recursive: true });
const sh = (cmd, args) => cp.execFileSync(cmd, args, { stdio: ['ignore', 'pipe', 'pipe'] });
const ENV_HZ = 60;
const result = { engine: { en: 'flite 2.2 voice rms (male, US English)', es: 'eSpeak NG 1.51 voice es-419 (Latin American Spanish, male), -s 150 -p 42' }, cues: {} };

FE.CUES.forEach((cue) => {
  const raw = path.join(out, cue.id + '_raw.wav'), fin = path.join(out, cue.id + '.wav');
  if (cue.lang === 'en') sh('flite', ['-voice', 'rms', '--setf', 'duration_stretch=1.3', '--setf', 'int_f0_target_mean=105', '-t', cue.tts, '-o', raw]);
  else sh('espeak-ng', ['-v', 'es-419', '-s', '150', '-p', '42', '-g', '3', '-w', raw, cue.tts]);
  // clean-up: band-limit, gentle compression, trim silence, 44.1k mono
  sh('ffmpeg', ['-y', '-v', 'error', '-i', raw, '-af',
    'highpass=f=90,lowpass=f=7600,acompressor=threshold=-20dB:ratio=2.2:attack=5:release=80,' +
    'silenceremove=start_periods=1:start_threshold=-45dB:start_silence=0.02,areverse,silenceremove=start_periods=1:start_threshold=-45dB:start_silence=0.02,areverse,' +
    'volume=2dB,aresample=44100', '-ac', '1', fin]);
  const dur = parseFloat(sh('ffprobe', ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', fin]).toString());
  // envelope for lip-sync
  const pcm = sh('ffmpeg', ['-v', 'error', '-i', fin, '-f', 's16le', '-ac', '1', '-ar', '16000', '-']);
  const n = pcm.length / 2, env = [];
  for (let f = 0; f * 16000 / ENV_HZ < n; f++) { const a = Math.round(f * 16000 / ENV_HZ), b = Math.min(n, Math.round((f + 1) * 16000 / ENV_HZ)); let s = 0, k = 0; for (let j = a; j < b; j++) { const v = pcm.readInt16LE(j * 2) / 32768; s += v * v; k++; } env.push(Math.sqrt(s / k)); }
  const mx = Math.max(...env) || 1; const envn = env.map((v) => +Math.min(1, v / (mx * 0.7)).toFixed(3));
  // word timing (proportional to syllable-ish weight + pause after punctuation)
  const words = cue.text.split(/\s+/);
  const wts = words.map((w) => Math.max(1, (w.toLowerCase().match(/[aeiouáéíóúü]+/g) || []).length) * 1.0 + (/[,.?!]$/.test(w) ? 0.45 : 0));
  const tot = wts.reduce((a, b) => a + b, 0); let acc = 0; const wt = words.map((w, i) => { const t0 = (acc / tot) * dur; acc += wts[i]; return { w, t0: +t0.toFixed(3), t1: +((acc / tot) * dur).toFixed(3) }; });
  result.cues[cue.id] = { file: path.relative(root, fin), dur: +dur.toFixed(3), envHz: ENV_HZ, env: envn, words: wt };
  console.log(cue.id, cue.lang, dur.toFixed(2) + 's', 'start', cue.t, 'end', (cue.t + dur).toFixed(2));
});
fs.writeFileSync(path.join(root, 'build/voices.json'), JSON.stringify(result));
fs.writeFileSync(path.join(root, 'src/voices-data.js'), '/* generated by tools/gen-voices.js — measured local-TTS durations, lip-sync envelopes, word timings */\nwindow.FE = window.FE || {}; window.FE.VOICES = ' + JSON.stringify(result) + ';\n');
