// Extract every spoken line (narration, dialogue, listen-and-repeat) from the lesson source.
// node tools/extract.mjs > tools/.lines.json
import vm from 'vm'; import fs from 'fs'; import path from 'path';
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const sandbox = { window: {}, console }; sandbox.window.window = sandbox.window; sandbox.window.NARR = {};
vm.createContext(sandbox);
const run = (f) => vm.runInContext(fs.readFileSync(path.join(root, 'src/js', f), 'utf8'), sandbox, { filename: f });
sandbox.window.FE = {}; sandbox.FE = sandbox.window.FE;
for (const f of ['00-util.js', '20-ipa.js', '21-ipa-data.js', '50-audio.js', '60-runner.js']) run(f);
for (const f of fs.readdirSync(path.join(root, 'src/js')).filter((x) => /^9[1-8]-/.test(x)).sort()) run(f);
const FE = sandbox.window.FE; const out = new Map();
const add = (voice, text, ph, who) => { const key = FE.speechKey(voice, text, ph); if (!out.has(key)) out.set(key, { key, voice, who, text: FE.stripMarkup(text), ph: ph || null }); };
for (const s of FE.L.segs) {
  for (const st of s.steps || []) {
    if (st[0] === 'nar') add(FE.VOICE.nar, st[1], (st[2] || {}).ph, 'nar');
    if (st[0] === 'say') add(FE.VOICE[st[1]], st[2], (st[3] || {}).ph, st[1]);
  }
  if (s.act && s.act.type === 'listen') for (const it of s.act.items) add(FE.VOICE.nar, it.t, it.ph, 'nar');
  // pronunciation cards replay the same clips; they are generated by the nar steps in 3.6
}
const arr = [...out.values()];
// every narrated word must have IPA too (captions show the narration word-over-IPA)
const miss = new Set(); for (const l of arr) for (const t of FE.tokens(l.text)) { if (t.punct || t.ov) continue; const k = t.word.toLowerCase().replace(/’/g, "'"); if (FE.IPA[k] == null) miss.add(k); }
console.log('NARRATION WORDS MISSING IPA (' + miss.size + '):', [...miss].sort().join(' '));
fs.writeFileSync(path.join(root, 'tools/.lines.json'), JSON.stringify(arr, null, 1));
console.log(arr.length + ' unique lines, ' + arr.reduce((a, b) => a + b.text.split(/\s+/).length, 0) + ' words, ' + arr.reduce((a, b) => a + b.text.length, 0) + ' characters');
console.log('segments:', FE.L.segs.length);
