#!/usr/bin/env python3
"""Generate narration clips with the local open-source Kokoro model (no API keys, no paid services).
   python tools/tts.py --model kokoro-v1.0.onnx --voices voices-v1.0.bin
   Reads tools/.lines.json (node tools/extract.mjs), writes release/audio/<key>.mp3 and src/js/05-narration.js.
   Clips already generated are reused (cache by key = hash of voice + phonemes + text)."""
import argparse, base64, json, os, subprocess, sys, wave
import numpy as np, soundfile as sf
from kokoro_onnx import Kokoro

ap = argparse.ArgumentParser()
ap.add_argument('--model', required=True); ap.add_argument('--voices', required=True)
ap.add_argument('--force', action='store_true')
a = ap.parse_args()
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
lines = json.load(open(os.path.join(root, 'tools/.lines.json')))
adir = os.path.join(root, 'release/audio'); os.makedirs(adir, exist_ok=True)
cache_p = os.path.join(root, 'tools/.tts-cache.json')
cache = json.load(open(cache_p)) if os.path.exists(cache_p) and not a.force else {}
k = Kokoro(a.model, a.voices)
SPEED = {'af_heart': 0.93}  # narrator slightly slower for adult learners
RATE = 30

def clean(t): return t.replace('“', '').replace('”', '').replace('’', "'").replace('‘', "'")

def trim(x, sr):
    thr = max(0.012, 0.02 * float(np.abs(x).max()))
    idx = np.where(np.abs(x) > thr)[0]
    if len(idx) == 0: return x
    pad = int(0.06 * sr)
    return x[max(0, idx[0] - pad): min(len(x), idx[-1] + pad)]

def words_timing(x, sr, nwords):
    """Estimate word boundaries inside a clip: split by internal pauses, then proportional by word length."""
    thr = max(0.01, 0.04 * float(np.abs(x).max())); win = int(0.01 * sr)
    env = np.array([np.abs(x[i:i + win]).max() for i in range(0, len(x) - win, win)])
    active = env > thr
    segs = []; st = None
    for i, v in enumerate(active):
        if v and st is None: st = i
        if not v and st is not None:
            segs.append([st, i]); st = None
    if st is not None: segs.append([st, len(active)])
    merged = []
    for s in segs:  # merge gaps shorter than 90 ms
        if merged and (s[0] - merged[-1][1]) < 9: merged[-1][1] = s[1]
        else: merged.append(s)
    if not merged: merged = [[0, len(active)]]
    return merged, 0.01

def process(item):
    voice = item['voice']; text = clean(item['text']); ph = item.get('ph')
    spd = SPEED.get(voice, 1.0)
    if ph: x, sr = k.create(ph, voice=voice, speed=spd, lang='en-us', is_phonemes=True)
    else: x, sr = k.create(text, voice=voice, speed=spd, lang='en-us')
    x = trim(x.astype(np.float32), sr)
    rms = float(np.sqrt(np.mean(x ** 2)) + 1e-9); x = x * (0.075 / rms)
    pk = float(np.abs(x).max())
    if pk > 0.92: x = x * (0.92 / pk)
    tmp = os.path.join(adir, item['key'] + '.wav'); sf.write(tmp, x, sr)
    mp3 = os.path.join(adir, item['key'] + '.mp3')
    subprocess.run(['ffmpeg', '-loglevel', 'error', '-y', '-i', tmp, '-ac', '1', '-ar', '24000', '-codec:a', 'libmp3lame', '-b:a', '48k', mp3], check=True)
    os.remove(tmp)
    dur = len(x) / sr
    # mouth envelope @30 Hz
    n = int(dur * RATE) + 1; w = int(sr / RATE)
    e = np.array([np.sqrt(np.mean(x[i * w:(i + 1) * w] ** 2)) if i * w < len(x) else 0 for i in range(n)])
    p95 = np.percentile(e, 95) + 1e-6
    env = np.clip(e / p95 * 200, 0, 255).astype(np.uint8)
    # word timings (estimated from pauses + word length)
    nw = len(text.split())
    merged, step = words_timing(x, sr, nw)
    toks = item['text'].split(); wt = np.array([len(t.strip('.,!?;:“”"') ) + 2 for t in toks], float)
    total = sum((b - a_) for a_, b in merged) * step
    cum = np.cumsum(wt) - wt / 2; cum = cum / wt.sum() * total
    words = [None] * len(toks)
    # map cumulative speech time -> clip time across merged segments
    def to_clip(sp):
        acc = 0
        for a_, b in merged:
            d = (b - a_) * step
            if sp <= acc + d: return a_ * step + (sp - acc)
            acc += d
        return merged[-1][1] * step
    edges = np.concatenate([[0], np.cumsum(wt) / wt.sum() * total])
    flat = []
    for i in range(len(toks)):
        flat += [round(to_clip(edges[i]), 3), round(to_clip(edges[i + 1]), 3)]
    return {'file': 'audio/%s.mp3' % item['key'], 'dur': round(dur, 3), 'rate': RATE, 'env': base64.b64encode(env.tobytes()).decode(), 'words': flat, 'voice': voice}

out = {}
done = 0
for item in lines:
    key = item['key']
    if key in cache and os.path.exists(os.path.join(adir, key + '.mp3')):
        out[key] = cache[key]; continue
    out[key] = process(item); cache[key] = out[key]; done += 1
    if done % 10 == 0: print('...', done, file=sys.stderr)
json.dump(cache, open(cache_p, 'w'))
js = '/* generated by tools/tts.py — do not edit. Local Kokoro (open-source) voices; word timings are estimated from pauses and word length. */\nwindow.NARR = ' + json.dumps(out, separators=(',', ':')) + ';\n'
open(os.path.join(root, 'src/js/05-narration.js'), 'w').write(js)
tot = sum(v['dur'] for v in out.values())
print('generated', done, 'new clips;', len(out), 'total;', round(tot, 1), 'seconds of speech;', round(os.path.getsize(os.path.join(root, 'src/js/05-narration.js')) / 1024), 'KB manifest')
