#!/usr/bin/env python3
"""Embed the subset WOFF2 fonts (assets/fonts-src) into css/fonts.css as data URIs so the
lesson works from file:// on any machine with no network. Fonts: Source Sans 3, Source Serif 4,
Charis SIL (IPA) - all SIL Open Font License 1.1 (licenses kept in assets/fonts-src)."""
import base64, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
src = root / "assets" / "fonts-src"
faces = [
  ("FE Sans",  "ss3-400.woff2",  400), ("FE Sans", "ss3-600.woff2", 600), ("FE Sans", "ss3-700.woff2", 700),
  ("FE Serif", "sserif-600.woff2", 600), ("FE Serif", "sserif-700.woff2", 700),
  ("FE IPA",   "charis-400.woff2", 400),
]
out = ["/* generated by tools/build-fonts.py - do not edit */"]
for fam, f, w in faces:
    b = base64.b64encode((src / f).read_bytes()).decode()
    out.append(f"@font-face{{font-family:'{fam}';font-weight:{w};font-style:normal;font-display:swap;src:url(data:font/woff2;base64,{b}) format('woff2');}}")
(root / "css" / "fonts.css").write_text("\n".join(out))
print("wrote css/fonts.css", (root / "css" / "fonts.css").stat().st_size, "bytes")
