#!/usr/bin/env python3
"""Generate the narration clips with Kokoro-82M (Apache-2.0, runs fully offline on CPU) and write audio/manifest.js.
Voices (American English): narrator af_heart, Maya af_bella, Alex am_michael (median f0 ~112 Hz, natural medium-low register,
no pitch shifting), Sam am_onyx, Nora af_nova.  No paid service is used.  See docs/VOICES.md for the honest assessment.

Setup (once):  python3 -m venv venv && venv/bin/pip install kokoro-onnx soundfile numpy onnxruntime
               download kokoro-v1.0.onnx and voices-v1.0.bin from
               https://github.com/thewh1teagle/kokoro-onnx/releases/tag/model-files-v1.0
Run:           node tools/dump-narration.mjs && venv/bin/python tools/gen-audio.py --model-dir <dir with the two files>
"""
import argparse, json, os, subprocess, sys, tempfile, numpy as np, soundfile as sf
ap = argparse.ArgumentParser(); ap.add_argument('--model-dir', required=True); ap.add_argument('--only', default='')
a = ap.parse_args()
here = os.path.dirname(os.path.abspath(__file__)); root = os.path.dirname(here)
from kokoro_onnx import Kokoro
k = Kokoro(os.path.join(a.model_dir, 'kokoro-v1.0.onnx'), os.path.join(a.model_dir, 'voices-v1.0.bin'))
data = json.load(open(os.path.join(here, 'cache', 'narration.json')))
SPEED = {'nar': .95, 'maya': .98, 'alex': .96, 'sam': .93, 'nora': .96}
os.makedirs(os.path.join(root, 'audio'), exist_ok=True)

def f0_stats(x, sr):
    fr = int(sr * .04); hop = int(sr * .02); vals = []
    for i in range(0, len(x) - fr, hop):
        s = x[i:i + fr]
        if np.sqrt(np.mean(s ** 2)) < .02: continue
        s = s - s.mean(); ac = np.correlate(s, s, 'full')[fr - 1:]
        lo, hi = int(sr / 300), int(sr / 70)
        if hi >= len(ac): continue
        j = np.argmax(ac[lo:hi]) + lo
        if ac[j] / ac[0] > .4: vals.append(sr / j)
    return (float(np.median(vals)), float(np.percentile(vals, 10)), float(np.percentile(vals, 90))) if vals else None

man = {}; stats = {}
for lid, ln in data['lines'].items():
    if a.only and a.only not in lid: continue
    who = ln['who']; voice = data['voices'][who]
    text = ln['text'].replace('’', "'")
    audio, sr = k.create(text, voice=voice, speed=SPEED.get(who, .96), lang='en-us')
    audio = np.asarray(audio, dtype=np.float32)
    # trim silence (keep 80 ms head, 160 ms tail)
    thr = .01; idx = np.where(np.abs(audio) > thr)[0]
    if len(idx): audio = audio[max(0, idx[0] - int(.08 * sr)): idx[-1] + int(.16 * sr)]
    fs = f0_stats(audio, sr)
    if fs: stats.setdefault(who, []).append(fs)
    with tempfile.TemporaryDirectory() as td:
        wav = os.path.join(td, 'x.wav'); sf.write(wav, audio, sr)
        out = os.path.join(root, 'audio', lid.replace('.', '_') + '.mp3')
        subprocess.run(['ffmpeg', '-loglevel', 'error', '-y', '-i', wav, '-af', 'loudnorm=I=-18:TP=-2:LRA=9', '-ar', '24000', '-ac', '1', '-codec:a', 'libmp3lame', '-b:a', '64k', out], check=True)
    # mouth envelope @25 fps (0-9) from the (normalised) wav
    env = []
    step = int(sr / 25)
    rms = [float(np.sqrt(np.mean(audio[i:i + step] ** 2))) for i in range(0, len(audio), step)]
    m = max(rms) or 1
    for r in rms: env.append(str(int(min(9, round((r / m) ** .7 * 9)))))
    dur = len(audio) / sr
    man[lid] = {'f': 'audio/' + lid.replace('.', '_') + '.mp3', 'd': round(dur, 2), 'env': ''.join(env), 'who': who, 'voice': voice}
    print(lid, voice, round(dur, 2), 's')
js = '/* generated by tools/gen-audio.py - do not edit */\nwindow.AUDIO_MANIFEST = ' + json.dumps(man, indent=0) + ';\n'
open(os.path.join(root, 'audio', 'manifest.js'), 'w').write(js)
json.dump({w: {'median_f0_hz': round(float(np.median([s[0] for s in v])), 1), 'p10': round(float(np.median([s[1] for s in v])), 1), 'p90': round(float(np.median([s[2] for s in v])), 1)} for w, v in stats.items()}, open(os.path.join(here, 'cache', 'voice-stats.json'), 'w'), indent=1)
print('done', len(man))
