#!/usr/bin/env python3
"""Import voice-over clips made elsewhere (for example in Speechelo) and rebuild audio/manifest.js.

1. Make one clip per line listed in docs/SPEECHELO-SCRIPT.txt and export each as MP3 or WAV.
2. Name each file with the line id, e.g.  ch2.intro.mp3  (or ch2_intro.mp3).
3. Run:  python3 tools/import-audio.py <folder with your clips>
Lines without a clip keep the current audio. Needs ffmpeg + ffprobe and numpy (pip install numpy).
Then rebuild the single file:  python3 tools/build-single.py
"""
import sys, os, json, subprocess, tempfile, glob
import numpy as np
here = os.path.dirname(os.path.abspath(__file__)); root = os.path.dirname(here)
if len(sys.argv) < 2: sys.exit(__doc__)
src = sys.argv[1]
nar = json.load(open(os.path.join(here, 'cache', 'narration.json')))
mp = os.path.join(root, 'audio', 'manifest.js')
man = json.loads(open(mp).read().split('=', 1)[1].rstrip().rstrip(';'))
done = 0
for lid, ln in nar['lines'].items():
    cands = [f for f in glob.glob(os.path.join(src, '*')) if os.path.splitext(os.path.basename(f))[0].lower() in (lid.lower(), lid.replace('.', '_').lower())]
    if not cands: continue
    f = cands[0]; out = os.path.join(root, 'audio', lid.replace('.', '_') + '.mp3')
    with tempfile.TemporaryDirectory() as td:
        wav = os.path.join(td, 'x.wav')
        subprocess.run(['ffmpeg', '-loglevel', 'error', '-y', '-i', f, '-ac', '1', '-ar', '24000', '-af', 'silenceremove=start_periods=1:start_threshold=-45dB,areverse,silenceremove=start_periods=1:start_threshold=-45dB,areverse,loudnorm=I=-18:TP=-2:LRA=9', wav], check=True)
        subprocess.run(['ffmpeg', '-loglevel', 'error', '-y', '-i', wav, '-codec:a', 'libmp3lame', '-b:a', '64k', out], check=True)
        raw = subprocess.run(['ffmpeg', '-loglevel', 'error', '-i', wav, '-f', 's16le', '-'], capture_output=True, check=True).stdout
        a = np.frombuffer(raw, dtype=np.int16).astype(np.float32) / 32768
    sr = 24000; step = sr // 25
    rms = [float(np.sqrt(np.mean(a[i:i + step] ** 2))) for i in range(0, len(a), step)]; m = max(rms) or 1
    man[lid] = {'f': 'audio/' + lid.replace('.', '_') + '.mp3', 'd': round(len(a) / sr, 2), 'env': ''.join(str(int(min(9, round((r / m) ** .7 * 9)))) for r in rms), 'who': ln['who'], 'voice': 'imported'}
    done += 1; print('imported', lid, man[lid]['d'], 's')
open(mp, 'w').write('/* generated by tools/gen-audio.py / tools/import-audio.py - do not edit */\nwindow.AUDIO_MANIFEST = ' + json.dumps(man, indent=0) + ';\n')
print(done, 'clips imported of', len(nar['lines']))
