// Embeds the logo, globe and fonts as base64 so video/index.html works from file:// with no network
// and the canvas never becomes cross-origin "tainted" (which would break recording/export).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "video", "assets");
const b64 = (f) => readFileSync(join(root, f)).toString("base64");

const out = `// GENERATED by tools/build-assets.mjs — do not edit.
window.FE = window.FE || {};
FE.ASSETS = {
  globe: "data:image/png;base64,${b64("globe.png")}",
  lockup: "data:image/png;base64,${b64("lockup.png")}",
  fonts: {
    display: "data:font/woff2;base64,${b64("fonts/playfair.woff2")}",
    displayItalic: "data:font/woff2;base64,${b64("fonts/playfair-italic.woff2")}",
    text: "data:font/woff2;base64,${b64("fonts/noto.woff2")}",
  },
};
`;
writeFileSync(join(root, "..", "js", "assets-data.js"), out);
console.log("assets-data.js", (out.length / 1024).toFixed(0), "KB");
